"""Add password_hash column

Revision ID: 2f82e35fc74c
Revises: 155ec45cc3ba
Create Date: 2025-07-17 16:18:30.424004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f82e35fc74c'
down_revision = '155ec45cc3ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_projects', sa.Column('shared_with_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('shared_projects_shared_with_id_fkey'), 'shared_projects', type_='foreignkey')
    op.create_foreign_key(None, 'shared_projects', 'users', ['shared_with_user_id'], ['id'])
    op.drop_column('shared_projects', 'shared_with_id')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    op.add_column('shared_projects', sa.Column('shared_with_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shared_projects', type_='foreignkey')
    op.create_foreign_key(op.f('shared_projects_shared_with_id_fkey'), 'shared_projects', 'users', ['shared_with_id'], ['id'])
    op.drop_column('shared_projects', 'shared_with_user_id')
    # ### end Alembic commands ###